### PR TITLE
Fixes #114 adds `/api` to appliance url

### LINKED ISSUE #114: Add support for Conjur Cloud
## Summary

When using the provider with Conjur Cloud, requires `/api` to be included in the appliance url.  Since this is supported between self-hosted and Conjur Cloud, hardcode of `/api` should be included.

## Steps to Reproduce

1. Get Conjur Cloud tenant.
2. Setup provider without `/api` on end of appliance url.
3. Witness failure.

## Expected Results

`/api` should be hardcoded into the request URL to not require it to be provided.

## Actual Results

Results in error with `/api` is not provided as part of appliance url.

## Reproducible

   * [x] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible
   
## Version/Tag number

* Affects every version

## Environment setup

* It doesn't matter. Affects every environment.

## Additional Information

n/a

### PR DESCRIPTION
**Pull request by infamousjoeg**
### Desired Outcome

Removes the requirement to add `/api` to the end of appliance urls for Conjur Cloud support.

### Implemented Changes

*Describe how the desired outcome above has been achieved with this PR. In
particular, consider:*

- _What's changed? Why were these changes made?_
Added an additional line of code to append `/api` to the `appliance_url` variable.
- _How should the reviewer approach this PR, especially if manual tests are required?_
Test, deploy, it will work successfully in all cases.
- _Are there relevant screenshots you can add to the PR description?_
No.

### Connected Issue/Story

Resolves #114 

CyberArk internal issue ID: n/a

### Definition of Done
*At least 1 todo must be completed in the sections below for the PR to be
merged.*

#### Changelog

- [x] The CHANGELOG has been updated, or
- [ ] This PR does not include user-facing changes and doesn't require a
  CHANGELOG update

#### Test coverage

- [ ] This PR includes new unit and integration tests to go with the code
  changes, or
- [x] The changes in this PR do not require tests

#### Documentation

- [ ] Docs (e.g. `README`s) were updated in this PR
- [ ] A follow-up issue to update official docs has been filed here: [insert issue ID]
- [x] This PR does not require updating any documentation

#### Behavior

- [ ] This PR changes product behavior and has been reviewed by a PO, or
- [ ] These changes are part of a larger initiative that will be reviewed later, or
- [x] No behavior was changed with this PR

#### Security

- [ ] Security architect has reviewed the changes in this PR,
- [ ] These changes are part of a larger initiative with a separate security review, or
- [x] There are no security aspects to these changes

### CODE REVIEW

File: conjur/provider.go [hunk 1]
```diff
@@ -66,6 +66,9 @@ func providerConfig(d *schema.ResourceData) (interface{}, error) {
 	if appliance_url != "" {
 		config.ApplianceURL = appliance_url
 	}
+	
+	// Add `/api` to appliance url for Conjur Cloud support
+	appliance_url += "/api"
```
Comment (jtuttle) [inline conjur/provider.go:71]: Huh, adding `/api` doesn't mess up a request to self-hosted?

**Review by jtuttle — APPROVED** [review]

**Review by jtuttle — CHANGES_REQUESTED** [review]
Okay, mind putting something in the CHANGELOG?

**Comment by infamousjoeg** [comment]
@jtuttle,

Added changes to CHANGELOG, bumped VERSION to v0.6.5, updated initial comment in PR #115 (above) to reflect changes to CHANGELOG made.

**Review by jtuttle — APPROVED** [review]
